# Generated by Django 3.1.3 on 2020-11-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='name',
        ),
    ]
