# Generated by Django 3.1.3 on 2020-11-23 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_shoppingcartitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.product'),
            preserve_default=False,
        ),
    ]
