# Generated by Django 3.1.3 on 2020-12-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201123_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(default='long description', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ImageUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.product')),
            ],
        ),
    ]
