# Generated by Django 3.1.3 on 2020-12-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201123_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
