# Generated by Django 3.1.3 on 2020-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20201212_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_country_code',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
