# Generated by Django 3.1.3 on 2020-12-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
