# Generated by Django 3.1.3 on 2020-12-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20201211_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
