# Generated by Django 3.1.3 on 2020-12-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20201212_1440'),
        ('API', '0007_auto_20201212_1545'),
    ]

    operations = [
    ]
