# Generated by Django 3.1.3 on 2020-12-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_product_rating'),
        ('API', '0011_auto_20201214_1815'),
    ]

    operations = [
    ]
