# Generated by Django 3.1.3 on 2020-12-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_merge_20201218_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
            ],
        ),
    ]
