# Generated by Django 3.1.3 on 2020-12-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_auto_20201220_1648'),
        ('API', '0013_auto_20201220_2319'),
    ]

    operations = [
    ]
