# Generated by Django 3.1.3 on 2021-01-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_order_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(default='vendor description', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='image_url',
            field=models.CharField(default='/images/1', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='title',
            field=models.CharField(default='Title', max_length=255),
            preserve_default=False,
        ),
    ]
