# Generated by Django 3.1.3 on 2021-01-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
