# Generated by Django 3.1.3 on 2021-01-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_auto_20210109_1933'),
        ('API', '0020_auto_20210115_2041'),
    ]

    operations = [
    ]
