# Generated by Django 3.1.3 on 2021-01-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_auto_20210109_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('argument', models.CharField(max_length=500)),
                ('is_seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
    ]
