# Generated by Django 3.1.3 on 2021-01-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_notification'),
        ('API', '0020_auto_20210115_2041'),
    ]

    operations = [
    ]
