# Generated by Django 3.1.3 on 2021-01-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_merge_20210121_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
