# Generated by Django 3.1.3 on 2021-01-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_merge_20210117_0012'),
        ('API', '0024_remove_productlistitem_name'),
    ]

    operations = [
    ]
