# Generated by Django 3.1.3 on 2021-01-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_merge_20210121_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
