# Generated by Django 3.1.3 on 2021-01-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_conversation_message'),
        ('API', '0024_auto_20210121_1247'),
    ]

    operations = [
    ]
