# Generated by Django 3.1.3 on 2021-01-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_merge_20210122_1923'),
        ('API', '0025_merge_20210122_1232'),
    ]

    operations = [
    ]
