version: '3.8'
services:
  web:
    build: .
    command: sh run-docker.sh
    volumes:
      - .:/code
    ports:
      - 8020:8080
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - BACKEND_DEBUG=True
      - BACKEND_ENVIRONMENT=getflix